[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stable_invoice = "36yRHdUHk63ZWUDpKiadoWm5UKxdD4j43KhKyHKFm9mU"

[programs.devnet]
stable_invoice = "36yRHdUHk63ZWUDpKiadoWm5UKxdD4j43KhKyHKFm9mU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tests/tsconfig.json -t 1000000 tests/**/*.ts"
