[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stable_invoice = "36yRHdUHk63ZWUDpKiadoWm5UKxdD4j43KhKyHKFm9mU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
